// pages/experiments.tsx
import React from 'react';
import 'isomorphic-fetch';
import PageLayout from '../components/PageLayout';
import PageContent from '../components/PageContent';
import styles from './experiments.scss';

interface Props {
  experiments: string[];
}

const Experiments = ({experiments}: Props) => (
  <PageLayout title='Experiments'>
    <PageContent>
      <p>I like to make lots of small projects. Here's where I stick lots of the web based ones.
        Be warned: I build them to work, not to look good </p>
      <ol className={styles.list}>
        {experiments.map((experiment, i) => (
          <li key={i} className={styles.link}>
            <a href={'/experiments/' + i}>{i}.&nbsp;
              <span className={styles.underlineyBit}>
                {typeof experiment === 'string' ? experiment : `Experiment #${i}`}
              </span>
            </a>
          </li>
        ))}
      </ol>
    </PageContent>
  </PageLayout>
);

Experiments.getInitialProps = async () => {
  const res = await fetch('//asherfoster.com/experiments/experiments.json');
  const names = (await res.json()) as string[];
  return {experiments: names || ['Failed to load']};
};

export default Experiments;

// src/app/experiments/experiments/experiments.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'af-experiments',
  templateUrl: './experiments.component.html',
  styleUrls: ['./experiments.component.scss']
})
export class ExperimentsComponent implements OnInit {
  experiments = new Array(7);

  constructor() { }

  ngOnInit() {
  }

}

<af-title>Experimental Experiments</af-title>
<div class="text">
  <p>
    I like to make lots of small projects. Here's where I stick lots of the web based ones.<br>
    Be warned: I build them to work, not to look good
  </p>
  <mat-nav-list>
    <a mat-list-item [routerLink]="'/experiments/' + i" *ngFor="let link of experiments; let i = index">Experiment #{{i}}</a>
  </mat-nav-list>
</div>
