// src/app/core/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'af-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<footer>
  <h4>&copy; Asher Foster 2017</h4>
  <a md-button target="_blank" rel="noopener" href="//twitter.com/asherfoster">Twitter</a>
  <a md-button target="_blank" rel="noopener" href="//github.com/asherfoster">GitHub</a>
</footer>

// components/Footer.tsx
import React from 'react';
import Link from 'next/link';
import styles from './Footer.scss';

export type FooterProps = {
  dark?: boolean;
};

const Footer = (props: FooterProps) => (
  <footer>
    <div className={styles.footerText + (props.dark ? ' ' + styles.footerDark : '')}>
      <p>&copy; Asher Foster 2019</p>
      <span className='flex'/>
      <div>
        <Link href='/'>
          <a >Home</a>
        </Link>
        <a href='//github.com/AsherFoster'>Github</a>
        <Link href='/contact'>
          <a>Contact</a>
        </Link>
      </div>
    </div>
  </footer>
);

export default Footer;
